version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:16.2.0
    environment:
      - POSTGRES_DB_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ${HOME}/.docker/postgresql/coses/:/bitnami/postgresql
  api:
    depends_on:
      - postgresql
    image: antoniomayk/coses:latest
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
    ports:
      - "8080:8080"
